### ISSUE TITLE
Node click event firing when mouse is released after dragging

### ISSUE THREAD

**Issue by frostbytedata** [vasturiano/3d-force-graph#67]
#### Issue description
It appears that the node clicked event will fire when the mouse button is released while hovering over a node, regardless of where the initial click down occurs. For instance, when I Click and drag white-space around the graph, it orbits the camera around the scene as expected. However, if while you are currently orbiting with the mouse button held down, if you then release the mouse button while coincidentally hovering over a node, it triggers the click event. This is undesirable as it is quite easy to be casually orbiting around the scene, and then abruptly experience unexpectedly whatever happens on the click event (in my case it navigates to a new view, and thus is extra disruptive to users).

#### Steps to reproduce the issue

1. Setup a basic graph with nodes and a registered click event function
2. Program an obvious event to occur in the node click event function such as navigation, notification, or change in the graph.
3. With the graph loaded and running, attempt to orbit around the scene by left clicking the mouse in empty white space. Hold the mouse button to stay in orbit mode.
4. While still in orbit mode, move the mouse so that is coincidentally hovering over any node in the graph.
5. Release the mouse button, and notice that even though you did not initially begin the orbit while clicking the node (we started orbit by clicking and holding in white space), the node click event is fired anyway, and the programmed change occurs unexpectedly. 

#### What's the expected result?

- The node click event should NOT fire if a user releases the mouse to leave orbit mode, while coincidentally hover over a node.

#### What's the actual result?

- The node click event is fired if a user releases the mouse to leave orbit mode, while coincidentally hover over a node.

#### Assumed Fix

Maybe this can be fixed with a flag that tracks whether or not the user is currently in orbit mode, and if they are, disable the firing of the click function when the mouse is released.

**Comment by vasturiano** [comment]
@frostbytedata thanks for reporting the issue. This has just been fixed in `v1.32.5`.

**Comment by s-r-jones** [comment]
@vasturiano I know this is closed but I still see this same behavior on the latest Safari. Happy to make a new issue if need be. 
eg https://vasturiano.github.io/3d-force-graph/example/click-to-focus/

**Comment by vasturiano** [comment]
@s-r-jones thanks for the heads up on this. After some investigation, seems like it's because Safari is not reporting the `pressure` value correctly when doing dragging interactions on the canvas. You can verify that by comparing this demo on Safari and other browsers: https://patrickhlauke.github.io/touch/tracker/tracker-force-pressure.html

Anyway, I've fixed the interaction so it doesn't rely on this attribute. I believe it fixed the issue. Can you re-try the same example?

**Comment by s-r-jones** [comment]
@vasturiano Thank you for the very quick response. I can confirm on desktop Safari the problem is gone. However I do see the same issue with Safari mobile on ios 12.4

here is a video demonstrating the behavior. https://drive.google.com/file/d/1eYlrKTYm_KA2Pmno3y1zl9t-YGF-Ldwa/view?usp=sharing

I sincerely appreciate your help. I am excited to show you what we make with your project!

**Comment by vasturiano** [comment]
@s-r-jones ok I've made some further improvements that should fix it in the mobile version too. Turns out Safari also doesn't expose `movementX`/`movementY` attributes on the touch event on mobile, that's what was causing the issue.

Could you re-test with the latest version?

And please do share a link to your app if you're using `3d-force-graph`! 😃

**Comment by s-r-jones** [comment]
@vasturiano I can confirm the updates work. Thank you so much! The project will be live this fall. I will send you updates then! Thanks again. Your project saved me months of work!
